-- Create the DB if it doesn't exist
SELECT 'CREATE DATABASE piq'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'piq')\gexec
-- Drop data
DROP TABLE IF EXISTS loans;
-- Set up our loans table
CREATE TABLE loans(
  id int,
  loan_amnt float(2),
  funded_amnt float(2),
  funded_amnt_inv float(2),
  term varchar(255),
  int_rate varchar(255),
  installment float(2),
  grade varchar(255),
  sub_grade varchar(255),
  emp_length varchar(255),
  home_ownership varchar(255),
  annual_inc float(2),
  verification_status varchar(255),
  issue_d varchar(255),
  loan_status varchar(255),
  description text,
  purpose varchar(255),
  title varchar(255),
  zip_code varchar(255),
  addr_state varchar(255),
  dti float(2),
  delinq_2yrs int,
  earliest_cr_line varchar(255),
  fico_range_low int,
  fico_range_high int,
  inq_last_6mths int,
  mths_since_last_delinq int,
  mths_since_last_record int,
  open_acc int,
  pub_rec int,
  revol_bal float(2),
  revol_util varchar(255),
  total_acc int,
  initial_list_status varchar(255),
  out_prncp int,
  out_prncp_inv int,
  total_pymnt float(2),
  total_pymnt_inv float(2),
  total_rec_prncp float(2),
  total_rec_int float(2),
  total_rec_late_fee float(2),
  recoveries float(2),
  collection_recovery_fee float(2),
  last_pymnt_d varchar(255),
  last_pymnt_amnt float(2),
  next_pymnt_d varchar(255),
  last_credit_pull_d varchar(255),
  last_fico_range_high int,
  last_fico_range_low int,
  collections_12_mths_ex_med int,
  mths_since_last_major_derog varchar(255),
  policy_code int,
  application_type varchar(255)
);
